name: Test Linux

on: 
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-linux:
    env:
      REPOSITORY_NAME: Test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.JX_PAT }}
        submodules: recursive
        lfs: true

    - name: Checkout Resource
      uses: actions/checkout@v2
      with:
        repository: 'SachiSakurane/ProjucerPackage'
        path: 'lib/ProjucerPackage'
        token: ${{ secrets.JX_PAT }}
        submodules: recursive
        lfs: true

    - name: Juce Dependency
      run: |
        sudo apt-get install freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev
        sudo apt-get install libwebkit2gtk-4.0-37

    - name: Projucer Setting
      run: |
        chmod 755 lib/ProjucerPackage/linux/setup.sh
        lib/ProjucerPackage/linux/setup.sh
        lib/ProjucerPackage/linux/Projucer --resave "Test/$REPOSITORY_NAME.jucer"

    - name: Build
      run: |
        cd Test/Builds/LinuxMakefile
        make
        ls


    # - name: Run Test
    #   run: |
    #     lldb -s ./bin/lldb_command.script "./Test/Builds/Linux/build/Debug/$REPOSITORY_NAME" > test.log
    #     if [$(grep "All tests completed successfully" test.log) = ""]; then
    #       echo "Test Failed"
    #       exit 1;
    #     else
    #       echo "Test Succeed"
    #     fi
