name: Test Linux

on: 
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-linux:
    env:
      PRODUCT_NAME: Test
      LOG_FILE_NAME: test.log
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Dependency Packages
      run: |
        sudo apt-get install -y xvfb libgtk-3-dev libxinerama-dev libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev libcurl4-openssl-dev

    - name: Build
      run: |
        cmake -B ninja-build -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja -C ninja-build Test -j 4

    - name: Run Test
      run: |
        xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" "./cmake-build/$PRODUCT_NAME/${PRODUCT_NAME}_artefacts/Release/$PRODUCT_NAME" > $LOG_FILE_NAME
        cat $LOG_FILE_NAME
        if [$(grep "FAILED!!" $LOG_FILE_NAME) = ""]; then
          echo "Test Succeed"
        else
          echo "Test Failed"
          exit 1;
        fi
