name: Test Linux

on: 
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependency Packages
      run: |
        sudo apt-get install -y libgtk-3-dev libxinerama-dev libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev libcurl4-openssl-dev

    - name: Build
      run: |
        cmake -B cmake-build -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-build --target Test -j 2

    - name: Run Test
      run: |
        lldb -s ./bin/lldb_command.script "./cmake-build/$PRODUCT_NAME/${PRODUCT_NAME}_artefacts/Release/$PRODUCT_NAME.app" > $LOG_FILE_NAME
        cat $LOG_FILE_NAME
        if [$(grep "FAILED!!" $LOG_FILE_NAME) = ""]; then
          echo "Test Succeed"
        else
          echo "Test Failed"
          exit 1;
        fi
