name: Test OSX

on: 
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-osx:
    env:
      PRODUCT_NAME: Test
      LOG_FILE_NAME: test.log
    runs-on: macOS-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build
      run: |
        cmake -B ninja-build -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja -C ninja-build Test -j 4

    - name: Run Test
      run: |
        "./cmake-build/$PRODUCT_NAME/${PRODUCT_NAME}_artefacts/Release/$PRODUCT_NAME.app/Contents/MacOS/$PRODUCT_NAME" > $LOG_FILE_NAME
        cat $LOG_FILE_NAME
        if [$(grep "FAILED!!" $LOG_FILE_NAME) = ""]; then
          echo "Test Succeed"
        else
          echo "Test Failed"
          exit 1;
        fi
