name: Test OSX

on: 
  push:
    branches:
      - master
      - develop

jobs:
  release-osx:
    env:
      REPOSITORY_NAME: Test
    runs-on: macOS-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.JX_PAT }}
        submodules: recursive
        lfs: true

    - name: Checkout Resource
      uses: actions/checkout@v2
      with:
        repository: 'SachiSakurane/ProjucerPackage'
        path: 'lib/ProjucerPackage'
        token: ${{ secrets.JX_PAT }}
        submodules: recursive
        lfs: true

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app/Contents/Developer'

    - name: Projucer Setting
      run: |
        chmod 755 ./lib/ProjucerPackage/osx/setup.sh
        ./lib/ProjucerPackage/osx/setup.sh
        ./lib/ProjucerPackage/osx/Projucer --resave "./Test/$REPOSITORY_NAME.jucer"

    - name: Build
      run: 
        xcodebuild -project "Test/Builds/MacOSX/$REPOSITORY_NAME.xcodeproj" -scheme "$REPOSITORY_NAME - App" -configuration Debug build

    - name: Run Test
      run: |
        lldb -s ./bin/lldb_command.script "./Test/Builds/MacOSX/build/Debug/$REPOSITORY_NAME.app" > test.log
        if [$(grep "All tests completed successfully" test.log) = ""]; then
          echo "Test Failed"
          exit 1;
        else
          echo "Test Succeed"
        fi
